# .github/FUNDING.yml

github: [DevsHero]
# หากคุณมีบัญชีอื่นๆ สามารถปลดคอมเมนต์และเติม username ได้เลยครับ
# patreon: devshero
# ko_fi: devshero
# buy_me_a_coffee: devshero
custom: ['https://github.com/sponsors/DevsHero']